apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-k8s-ingress-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: flask.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-k8s-ingress-demo
                port:
                  number: 80
